export const categories = [
    "All",
    "Website",
    "Music",
    "Gaming",
    "Node.js",
    "React.js",
    "TypeScript",
    "Coding",
    "Data analysis",
    "JavaScript",
    "Web design",
    "Tailwind",
    "HTML",
    "CSS",
    "Next.js",
    "Express.js",
  ];
  
  export const sidebarLinks = [
    {
      categoryTitle: "",
      links: [
        {
          icon: "Home",
          title: "Home",
          url: "#",
        },
        {
          icon: "Video",
          title: "Shorts",
          url: "#",
        },
        {
          icon: "ListVideo",
          title: "Subscription",
          url: "#",
        },
      ],
    },
    {
      categoryTitle: "",
      links: [
        {
          icon: "User",
          title: "You",
          url: "#",
        },
        {
          icon: "History",
          title: "History",
          url: "#",
        },
      ],
    },
    {
      categoryTitle: "Explore",
      links: [
        {
          icon: "Flame",
          title: "Trending",
          url: "#",
        },
        {
          icon: "Music",
          title: "Shorts",
          url: "#",
        },
        {
          icon: "Gamepad2",
          title: "Gaming",
          url: "#",
        },
        {
          icon: "Trophy",
          title: "Sports",
          url: "#",
        },
      ],
    },
    {
      categoryTitle: "More from YouTube",
      links: [
        {
          icon: "Youtube",
          title: "YouTube Pro",
          url: "#",
        },
        {
          icon: "CirclePlay",
          title: "YouTube Music",
          url: "#",
        },
        {
          icon: "Blocks",
          title: "YouTube Kids",
          url: "#",
        },
      ],
    },
    {
      categoryTitle: "",
      links: [
        {
          icon: "Settings",
          title: "Settings",
          url: "#",
        },
        {
          icon: "Flag",
          title: "Report",
          url: "#",
        },
        {
          icon: "CircleHelp",
          title: "Help",
          url: "#",
        },
        {
          icon: "MessageSquareWarning",
          title: "Feedback",
          url: "#",
        },
      ],
    },
  ];
  
  export const videos = [
    {
      id: "3",
      title: "Top 10 Easy To Create JavaScript Games For Beginners",
      channel: {
        name: "CodingNepal",
        url: "https://www.youtube.com/@CodingNepal",
        logo: "https://yt3.googleusercontent.com/VYLLrblIs_umHCFyK_-q5HJLfB-aDc5ax94uUjNaU5IQXZAlMn6bMVPG-AaLR3-k5_HcBMcI6MA=s176-c-k-c0x00ffffff-no-rj",
      },
      views: "27K",
      postedAt: "4 months ago",
      duration: "10:03",
      thumbnailURL: "https://i.ytimg.com/vi/OORUHkgg4IM/maxresdefault.jpg",
      videoURL: "https://youtu.be/OORUHkgg4IM",
    },
    {
      id: "2",
      title: "Create Responsive Website with Login & Registration Form",
      channel: {
        name: "CodingNepal",
        url: "https://www.youtube.com/@CodingNepal",
        logo: "https://yt3.googleusercontent.com/VYLLrblIs_umHCFyK_-q5HJLfB-aDc5ax94uUjNaU5IQXZAlMn6bMVPG-AaLR3-k5_HcBMcI6MA=s176-c-k-c0x00ffffff-no-rj",
      },
      views: "68K",
      postedAt: "9 months ago",
      duration: "29:43",
      thumbnailURL: "https://i.ytimg.com/vi/YEloDYy3DTg/maxresdefault.jpg",
      videoURL: "https://youtu.be/YEloDYy3DTg",
    },
    {
      id: "7",
      title: "Create a Responsive Calculator in HTML CSS & JavaScript",
      channel: {
        name: "CodingLab",
        url: "https://www.youtube.com/@CodingLabYT",
        logo: "https://yt3.googleusercontent.com/uITV5E7auiZMDD_BwhVRJMHXXY6qQc0GqBgVyP5LWYTmeRlUP2Dc945UlIbODvztd96ReOts=s176-c-k-c0x00ffffff-no-rj",
      },
      views: "30K",
      postedAt: "2 year ago",
      duration: "11:13",
      thumbnailURL: "https://i.ytimg.com/vi/cHkN82X3KNU/maxresdefault.jpg",
      videoURL: "https://youtu.be/cHkN82X3KNU",
    },
    {
      id: "9",
      title: "Responsive Admin Dashboard Panel in HTML CSS & JavaScript",
      channel: {
        name: "CodingLab",
        url: "https://www.youtube.com/@CodingLabYT",
        logo: "https://yt3.googleusercontent.com/uITV5E7auiZMDD_BwhVRJMHXXY6qQc0GqBgVyP5LWYTmeRlUP2Dc945UlIbODvztd96ReOts=s176-c-k-c0x00ffffff-no-rj",
      },
      views: "161K",
      postedAt: "1 year ago",
      duration: "1:37:13",
      thumbnailURL: "https://i.ytimg.com/vi/AyV954yKRSw/maxresdefault.jpg",
      videoURL: "https://youtu.be/AyV954yKRSw",
    },
    {
      id: "4",
      title: "Create Text Typing Effect in HTML CSS & Vanilla JavaScript",
      channel: {
        name: "CodingNepal",
        url: "https://www.youtube.com/@CodingNepal",
        logo: "https://yt3.googleusercontent.com/VYLLrblIs_umHCFyK_-q5HJLfB-aDc5ax94uUjNaU5IQXZAlMn6bMVPG-AaLR3-k5_HcBMcI6MA=s176-c-k-c0x00ffffff-no-rj",
      },
      views: "17K",
      postedAt: "10 months ago",
      duration: "9:27",
      thumbnailURL: "https://i.ytimg.com/vi/DLs1X9T1GcY/maxresdefault.jpg",
      videoURL: "https://youtu.be/DLs1X9T1GcY",
    },
    {
      id: "1",
      title: "Multiple File Uploading in HTML CSS & JavaScript",
      channel: {
        name: "CodingNepal",
        url: "https://www.youtube.com/@CodingNepal",
        logo: "https://yt3.googleusercontent.com/VYLLrblIs_umHCFyK_-q5HJLfB-aDc5ax94uUjNaU5IQXZAlMn6bMVPG-AaLR3-k5_HcBMcI6MA=s176-c-k-c0x00ffffff-no-rj",
      },
      views: "7.4K",
      postedAt: "3 weeks ago",
      duration: "30:20",
      thumbnailURL: "https://i.ytimg.com/vi/_RSaI2CxlXU/maxresdefault.jpg",
      videoURL: "https://youtu.be/_RSaI2CxlXU",
    },
    {
      id: "5",
      title: "How to Make Chrome Extension in HTML CSS & JavaScript",
      channel: {
        name: "CodingNepal",
        url: "https://www.youtube.com/@CodingNepal",
        logo: "https://yt3.googleusercontent.com/VYLLrblIs_umHCFyK_-q5HJLfB-aDc5ax94uUjNaU5IQXZAlMn6bMVPG-AaLR3-k5_HcBMcI6MA=s176-c-k-c0x00ffffff-no-rj",
      },
      views: "24K",
      postedAt: "1 year ago",
      duration: "19:27",
      thumbnailURL: "https://i.ytimg.com/vi/coj-l7IrwGU/maxresdefault.jpg",
      videoURL: "https://youtu.be/coj-l7IrwGU",
    },
    {
      id: "8",
      title: "How to make Responsive Image Slider in HTML CSS & JavaScript",
      channel: {
        name: "CodingLab",
        url: "https://www.youtube.com/@CodingLabYT",
        logo: "https://yt3.googleusercontent.com/uITV5E7auiZMDD_BwhVRJMHXXY6qQc0GqBgVyP5LWYTmeRlUP2Dc945UlIbODvztd96ReOts=s176-c-k-c0x00ffffff-no-rj",
      },
      views: "1M",
      postedAt: "1 year ago",
      duration: "37:13",
      thumbnailURL: "https://i.ytimg.com/vi/q4RgxiDM6v0/maxresdefault.jpg",
      videoURL: "https://youtu.be/q4RgxiDM6v0",
    },
    {
      id: "6",
      title: "How to make Responsive Card Slider in HTML CSS & JavaScript",
      channel: {
        name: "CodingLab",
        url: "https://www.youtube.com/@CodingLabYT",
        logo: "https://yt3.googleusercontent.com/uITV5E7auiZMDD_BwhVRJMHXXY6qQc0GqBgVyP5LWYTmeRlUP2Dc945UlIbODvztd96ReOts=s176-c-k-c0x00ffffff-no-rj",
      },
      views: "42K",
      postedAt: "1 year ago",
      duration: "23:45",
      thumbnailURL: "https://i.ytimg.com/vi/qOO6lVMhmGc/maxresdefault.jpg",
      videoURL: "https://youtu.be/qOO6lVMhmGc",
    },
    {
      id: "11",
      title: "Flipping Card UI Design in HTML & CSS",
      channel: {
        name: "CodingLab",
        url: "https://www.youtube.com/@CodingLabYT",
        logo: "https://yt3.googleusercontent.com/uITV5E7auiZMDD_BwhVRJMHXXY6qQc0GqBgVyP5LWYTmeRlUP2Dc945UlIbODvztd96ReOts=s176-c-k-c0x00ffffff-no-rj",
      },
      views: "85K",
      postedAt: "2 months ago",
      duration: "12:24",
      thumbnailURL: "https://i.ytimg.com/vi/20Qb7pNMv-4/maxresdefault.jpg",
      videoURL: "https://youtu.be/20Qb7pNMv-4",
    },
    {
      id: "13",
      title: "How To Create A Responsive Website Using HTML & CSS",
      channel: {
        name: "MicroCoding",
        url: "https://www.youtube.com/@MicroCoding.",
        logo: "https://yt3.googleusercontent.com/pz6ex8LxSI-8A4S-sFNZl3QylmXToJWwD7z5zXP-IdSIfFTWPMXCGf8fxKjhEs3CwYBe-S2gzM8=s176-c-k-c0x00ffffff-no-rj",
      },
      views: "7.2K",
      postedAt: "2 weeks ago",
      duration: "1:18:24",
      thumbnailURL: "https://i.ytimg.com/vi/tECCCaErjtM/maxresdefault.jpg",
      videoURL: "https://youtu.be/tECCCaErjtM",
    },
    {
      id: "15",
      title: "Create Text Typing Effect in HTML CSS & Vanilla JavaScript",
      channel: {
        name: "CodingNepal",
        url: "https://www.youtube.com/@CodingNepal",
        logo: "https://yt3.googleusercontent.com/VYLLrblIs_umHCFyK_-q5HJLfB-aDc5ax94uUjNaU5IQXZAlMn6bMVPG-AaLR3-k5_HcBMcI6MA=s176-c-k-c0x00ffffff-no-rj",
      },
      views: "17K",
      postedAt: "10 months ago",
      duration: "9:27",
      thumbnailURL: "https://i.ytimg.com/vi/DLs1X9T1GcY/maxresdefault.jpg",
      videoURL: "https://youtu.be/DLs1X9T1GcY",
    },
    {
      id: "12",
      title: "Beautiful Login Form using HTML & CSS only",
      channel: {
        name: "MicroCoding",
        url: "https://www.youtube.com/@MicroCoding.",
        logo: "https://yt3.googleusercontent.com/pz6ex8LxSI-8A4S-sFNZl3QylmXToJWwD7z5zXP-IdSIfFTWPMXCGf8fxKjhEs3CwYBe-S2gzM8=s176-c-k-c0x00ffffff-no-rj",
      },
      views: "4.2K",
      postedAt: "4 days ago",
      duration: "18:24",
      thumbnailURL: "https://i.ytimg.com/vi/jkThO1GIP9Y/maxresdefault.jpg",
      videoURL: "https://youtu.be/jkThO1GIP9Y",
    },
  ];